name: ml4pmssm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - uproot
  - pyyaml

